"""empty message

Revision ID: 6b7dd172b005
Revises: 
Create Date: 2023-06-04 21:09:21.036699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b7dd172b005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_index('ix_game_session_id')

    op.drop_table('game_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draws', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='game_session_pkey')
    )
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.create_index('ix_game_session_id', ['id'], unique=False)

    # ### end Alembic commands ###
